
tests-y			+= builtins_test.o

tests-obj-y		+= src/libc/common/builtins/__ctzsi2.o
tests-obj-y		+= src/libc/common/builtins/__clzsi2.o
tests-obj-y		+= src/libc/common/builtins/__ffsdi2.o

libex-y			+= src/libc/libc-$(SRCARCH)-none.a

