
obj-y			+= binaries.o
obj-y			+= filedesc.o
obj-y			+= exec.o
obj-y			+= fork.o
obj-y			+= memory.o
obj-y			+= process.o
obj-y			+= scheduler.o
obj-y			+= select.o
obj-y			+= signal.o
obj-y			+= init.o
obj-y			+= timer.o

