
obj-y			+= devfs/
obj-y			+= procfs/
obj-$(CONFIG_MALLOC_FS)	+= mallocfs/
obj-$(CONFIG_MINIX_FS)	+= minix/

obj-y			+= access.o
obj-y			+= bufcache.o
obj-y			+= device.o
obj-y			+= fileptr.o
obj-y			+= nop.o
obj-y			+= pipe.o
obj-y			+= vfs.o

