
obj-y			+= devfs/
obj-y			+= procfs/
obj-y			+= partition/
obj-$(CONFIG_MINIX_FS)	+= minix/
obj-$(CONFIG_EXT2_FS)	+= ext2/

obj-y			+= access.o
obj-y			+= bufcache.o
obj-y			+= device.o
obj-y			+= fileptr.o
obj-y			+= nop.o
obj-y			+= pipe.o
obj-y			+= vfs.o

