
# TODO this doesn't actually cause a rebuilt of minix.c, only of built-in.o
#extra-y			+= minix.h minix-v1.h super.h zones.h bitmaps.h inodes.h vnodes.h dir.h mkfs.h minix.c bitmaps.c

obj-y			+= minix.o

