
tests-y			+= queue_test.o
tests-y			+= ringbuffer_test.o
tests-y			+= strarray_test.o
tests-y			+= iovec_test.o

tests-obj-y		+= src/kernel/utils/iovec.o
tests-obj-y		+= src/kernel/utils/strarray.o

libex-y			+= src/libc/libc-$(SRCARCH)-none.a

