
tests-y			+= queue_test.o
tests-y			+= ringbuffer_test.o
tests-y			+= strarray_test.o

tests-extra-y		+= $(src-root)/src/kernel/utils/iovec.host.o
tests-extra-y		+= $(src-root)/src/kernel/utils/strarray.host.o
tests-extra-y		+= $(src-root)/tests/printk.host.o

