
tests-y			+= queue_test.o
tests-y			+= ringbuffer_test.o
tests-y			+= strarray_test.o
tests-y			+= iovec_test.o

tests-extra-y		+= $(src-root)/src/kernel/utils/iovec.host.o
tests-extra-y		+= $(src-root)/src/kernel/utils/strarray.host.o
tests-extra-y		+= $(src-root)/tests/printk.host.o

bare-tests-extra-y	+= $(src-root)/src/kernel/utils/iovec.o
bare-tests-extra-y	+= $(src-root)/src/kernel/utils/strarray.o
bare-tests-extra-y	+= $(src-root)/tests/printk.o

libex-y			+= src/libc/libc-$(SRCARCH)-none.a

