
subdir-$(CONFIG_BOOT)		+= boot
subdir-$(CONFIG_COMMANDS)	+= commands
subdir-$(CONFIG_KERNEL)		+= kernel
subdir-$(CONFIG_MONITOR)	+= monitor

diskimage-dirs			+= home/
diskimage-dirs			+= proc/
diskimage-dirs			+= media/

